spring:
    config:
        import: optional:file:.env[.properties]

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${DB_DOMAIN}:${DB_PORT}/${DB_NAME}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true

oauth:
    kakao:
        client-id: ${KAKAO_REST_API_KEY}
        redirect-uri: http://localhost:8080/oauth/kakao/callback
        token-uri: https://kauth.kakao.com/oauth/token
        user-info-uri: https://kapi.kakao.com/v2/user/me

jwt:
    secret: ${JWT_SECRET_KEY}
    expiration: 3600000 # 1시간

frontend:
    redirect-base-url: ${FRONTEND_REDIRECT_BASE_URL}