spring:
    config:
        import: optional:file:.env[.properties]

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${DB_DOMAIN}:${DB_PORT}/${DB_NAME}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}

    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true

    # OAuth2 Client 설정
    security:
        oauth2:
            client:
                registration:
                    kakao:
                        client-id: ${KAKAO_REST_API_KEY}
                        client-secret: ${KAKAO_CLIENT_SECRET}
                        redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
                        authorization-grant-type: authorization_code
                        scope:
                            - profile_nickname
                            - account_email
                        client-authentication-method: client_secret_post
                        client-name: Kakao
                    google:
                        client-id: ${GOOGLE_CLIENT_ID}
                        client-secret: ${GOOGLE_CLIENT_SECRET}
                        redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
                        authorization-grant-type: authorization_code
                        scope:
                            - email
                            - profile
                        client-authentication-method: client_secret_post
                        client-name: Google
                provider:
                    kakao:
                        authorization-uri: https://kauth.kakao.com/oauth/authorize
                        token-uri: https://kauth.kakao.com/oauth/token
                        user-info-uri: https://kapi.kakao.com/v2/user/me
                        user-name-attribute: id
                    google:
                        authorization-uri: https://accounts.google.com/o/oauth2/auth
                        token-uri: https://oauth2.googleapis.com/token
                        user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
                        user-name-attribute: sub
jwt:
    secret: ${JWT_SECRET_KEY}
    expiration: 3600000 # 1시간
    cookie:
        name: jeukhaeng_access_token
        max-age: 3600 # 1시간
        path: /
        domain:
        secure: false # 로컬 개발 환경에서는 false, 프로덕션에서는 true
        http-only: true
        same-site: lax # lax, strict, none 중 선택

frontend:
    redirect-base-url: ${FRONTEND_REDIRECT_BASE_URL}

api:
    api-base-url: ${TOUR_API_SERVICE_KEY}
    encoded-service-key: ${ENCODED_SERVICE_KEY}